### ISSUE TITLE
IngestRabbit Issue

### ISSUE THREAD

**Issue by cjkrome** [pacifica/pacifica#13]
On a second failed attempt at posting a file to the ingest /upload endpoint, the ingestrabbit service begins throwing the following errors repeatedly:

```
ingestfrontend_1 | Mon Aug 13 10:35:13 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /upload (ip x.x.x.x) !!!
ingestrabbit_1 | 2018-08-13 10:35:13.712 [warning] <0.24043.1> closing AMQP connection <0.24043.1> (x.x.x.x:40982 -> x.x.x.x:5672, vhost: '/', user: 'guest'):
ingestrabbit_1 | client unexpectedly closed TCP connection
ingestrabbit_1 | 2018-08-13 10:35:13.724 [info] <0.24058.1> accepting AMQP connection <0.24058.1> (x.x.x.x:40984 -> x.x.x.x:5672)
ingestrabbit_1 | 2018-08-13 10:35:13.726 [info] <0.24058.1> connection <0.24058.1> (x.x.x.x:40984 -> x.x.x.x:5672): user 'guest' authenticated and granted access to vhost '/'
```

Reducing the celery version in the ingestfrontend container seems to fix the problem for the moment:

`docker exec -it pacifica_ingestfrontend_1 pip install 'celery<4.2'`

**Comment by dmlb2000** [comment]
There are a couple of solutions for this, I'd like to give both and some arguments for and against. Feel free to comment about them if you like.

RabbitMQ is designed as a single system multi-user system. Each user can have different permissions to any number of message queues supported within the one instance of RabbitMQ. 

Redis is designed as a remote in-memory cache and message broker. Redis supports builtin types that map directly to objects in different languages. As multiple clients can talk to the same Redis service it can act as a message broker.

The use of RabbitMQ is simply the default broker for the Python Celery library. The usage of a Celery broker in the docker-compose file are slightly at odds with how RabbitMQ was intended to be used. The reason for multiple Celery brokers in the docker-compose file is to show the independence of each service. If one RabbitMQ service were used, the configuration for each service would be linked to the one RabbitMQ service. This could present a false sense of dependence between the different parts of Pacifica. 

## Solution 1 - Single RabbitMQ & Downgrade Celery

Don't worry about the false sense of dependence between the services. Just back Celery down a version and combine all RabbitMQ services to a single service accessed with multi services and user accounts.

## Solution 2 - Replace RabbitMQ with Redis

This should not involve a downgrade of Celery. However, extensive environment variables would need to be set to invoke each service into using Redis. Though this might be a good example anyhow.

**Comment by dmlb2000** [comment]
My thought is to replace RabbitMQ with Redis as I've not seen these sort of connection issues with Redis it's a far simpler service to manage and interface with. Additionally, the limitations in it's administrative features aren't necessary in the Docker environment anyway.

**Comment by dmlb2000** [comment]
With the pre-release of Pacifica v1.0 alpha this is closed.

The docker containers in question have testing in their own repositories now. This means the tagged containers should match the tagged version of the software and the containers should work.

If this is still an issue it should be filed with their respective repository.
