### ISSUE TITLE
Consider cross-project pip requirements deps major version locking

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica#14]
Technical task that could lead into larger version management conversations.

Think about project level major version locking or version freeze events. Also, consider versioning all Pacifica related projects in a consistent "project-oriented" fashion once we move to pip package versioning.

**Comment by dmlb2000** [comment]
I think the plan for this is to move the major version of all packages along with the major versions of Pacifica. With v0.98.0 version of Pacifica tagged now we should be able to close this as we are locking the submodules from here for system integration testing.
