### ISSUE TITLE
[Recommendation] Maintain detailed project wide CHANGELOG

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica#16]
This is really a ticket for the project as a whole (i.e. sub-projects) in terms of this issue.

We should try to maintain some semblance of a detailed account of changes as part of the CHANGELOG procedures. As a release is made, it would be awesome to see the changes to expect (breaking or otherwise) as we move into the `1.0.0` land and beyond. This also includes links to any update procedures necessary to implement as one goes from version a>>b>>c for example.

Cheers!

**Comment by dmlb2000** [comment]
I'm going to high jack this to track the additions to the ChangeLogs required for 1.0.

 - [x] archiveinterface - https://github.com/pacifica/pacifica-archiveinterface/commit/a473b1aa22b4df2e7eb23c7aaecc14da655ec08d
 - [x] cartd - https://github.com/pacifica/pacifica-cartd/commit/c1ba927655892130a219522512ab7237999df8a9
 - [x] cli - https://github.com/pacifica/pacifica-cli/commit/48d2f62ab635c92dc4c643b17c06d8d02b906b93
 - [x] dispatcher - https://github.com/pacifica/pacifica-dispatcher/commit/204b315e397a6b2444ef827d45262cae0a8af370
 - [x] ingest - https://github.com/pacifica/pacifica-ingest/commit/50a0a23f685773d0fc6d1f0f3bf783b429bbb821
 - [x] metadata - https://github.com/pacifica/pacifica-metadata/commit/a1d4a6cb207dad77b48bb68825f640cdc8d99afe
 - [x] notifications - https://github.com/pacifica/pacifica-notifications/commit/0bf2e929c5e743b2cdb83b08fb4e304e7c8c9902
 - [x] policy - https://github.com/pacifica/pacifica-policy/commit/3bd252652cb0b7d84b9d5a6966d65a3ab7222807
 - [x] proxy - https://github.com/pacifica/pacifica-proxy/commit/ce830621bb9258a974d4bc0bb655c7a2628c4dd0
 - [x] python downloader library - https://github.com/pacifica/pacifica-python-downloader/commit/2ebda240925125d2b0e86bb69d65b11af62a8260
 - [x] python uploader library - https://github.com/pacifica/pacifica-python-uploader/commit/608156d6505ea0384840de16d3b9e2531cc680a5
 - [x] uniqueid - https://github.com/pacifica/pacifica-uniqueid/commit/aaec06a313601a1cfaecf9b3ecbb54daf91b3aa7
