### ISSUE TITLE
Unexpected results while working through Pacifica examples

### ISSUE THREAD

**Issue by stefangary** [pacifica/pacifica#17]
# Summary

I started Pacifica with docker-compose up and while it seems that the containers are running as they should, some of the examples in the pacifica documentation fail, details below. Is this something that needs to be adjusted within the containers or a user error on my part?  Also, when I run docker-compose ps, all the containers are up except pacifica_elasticdb_1 and pacifica_jupytervolume.  Is that normal?

Thank you for considering my questions and I would be happy to provide more information.

# System info
Same results in either Ubuntu 16.04 and 18.04
Docker version 18.09.5, build e8ff056
docker-compose version 1.24.0, build 0aa59064

# First set of examples
Based on https://pacifica-archiveinterface.readthedocs.io/en/latest/exampleusage.html,
GET, PUT, HEAD all work as expected.
POST fails because "Client must specify Content-Length" but that is already known in the HEAD operation.
PATCH fails because "Expected an entity of content type application/json, text/javascript" but the uploaded file is .json as specified in the example.
Terminal output below.

> curl -X GET http://localhost:8080
{"message": "Pacifica Archive Interface Up and Running"}

> curl -X PUT -H 'Last-Modified: Sun, 06 Nov 1994 08:49:37 GMT' --upload-file foo.txt http://localhost:8080/12345
{"message": "File added to archive", "total_bytes": 36}

>curl -o foo.txt http://localhost:8080/12345
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    36    0    36    0     0   2571      0 --:--:-- --:--:-- --:--:--  2571

> curl -I -X HEAD http://localhost:8080/12345
HTTP/1.1 204 No Content
X-Pacifica-File-Storage-Media: disk
X-Pacifica-Messsage: File was found
X-Content-Length: 36
X-Pacifica-File: /srv/12345
X-Pacifica-Ctime: 1557152541.06
Server: CherryPy/17.4.1
Last-Modified: 1557152540.07
Allow: DELETE, GET, HEAD, PATCH, POST, PUT
Date: Mon, 06 May 2019 14:23:33 GMT
Content-Type: application/json
X-Pacifica-Bytes-Per-Level: (36L,)

> curl -X POST http://localhost:8080/12345
{"status": "411 Length Required", "message": "Client must specify Content-Length.", "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 682, in _do_respond\n    self.body.process()\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py\", line 978, in process\n    raise cherrypy.HTTPError(411)\nHTTPError: (411, None)\n", "version": "17.4.1"}

> curl -X PATCH --upload-file original_path.json http://localhost:8080/67890
{"status": "415 Unsupported Media Type", "message": "Expected an entity of content type application/json, text/javascript", "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 682, in _do_respond\n    self.body.process()\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py\", line 983, in process\n    super(RequestBody, self).process()\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py\", line 558, in process\n    self.default_proc()\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cperror.py\", line 416, in __call__\n    raise self\nHTTPError: (415, u'Expected an entity of content type application/json, text/javascript')\n", "version": "17.4.1"}

> cat original_path.json 
{
    "path": "/srv/12345"
}

# Second set of examples
In section 4.1 of https://buildmedia.readthedocs.org/media/pdf/pacifica-metadata/latest/pacifica-metadata.pdf,
as before, PUT works but the database query with GET fails.
Interestingly (compared to the first set of examples) the POST operation exits OK, but fails to actually update the file.

> more create.json 
{
"_id": 127,
"email_address": "john@doe.com",
"first_name": "John",
"last_name": "Doe",
"middle_initial": "",
"network_id": "guest"
}

> curl -X PUT -T create.json http://localhost:8080/users
{"message": "File added to archive", "total_bytes": 135}

> curl -X GET 'http://localhost:8080/users?_id=127'
{"status": "404 Not Found", "message": "Unexpected query string parameters: _id", "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py\", line 60, in __call__\n    raise sys.exc_info()[1]\nHTTPError: (404, 'Unexpected query string parameters: _id')\n", "version": "17.4.1"}

> more update.json 
{
"network_id": "example"
}

> curl -X POST -T update.json 'http://localhost:8080/users'
{"message": "File was staged", "file": "users"}

> curl -X GET http://localhost:8080/users
{
"_id": 127,
"email_address": "john@doe.com",
"first_name": "John",
"last_name": "Doe",
"middle_initial": "",
"network_id": "guest"
}

> curl -X POST 'http://localhost:8080/users'
{"status": "411 Length Required", "message": "Client must specify Content-Length.", "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 682, in _do_respond\n    self.body.process()\n  File \"/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py\", line 978, in process\n    raise cherrypy.HTTPError(411)\nHTTPError: (411, None)\n", "version": "17.4.1"}

**Comment by dmlb2000** [comment]
> # Summary
> I started Pacifica with docker-compose up and while it seems that the containers are running as they should, some of the examples in the pacifica documentation fail, details below. Is this something that needs to be adjusted within the containers or a user error on my part? Also, when I run docker-compose ps, all the containers are up except pacifica_elasticdb_1 and pacifica_jupytervolume. Is that normal?

No, both of them should show up. However, there are some tricks to getting elasticsearch started on Linux in docker. Please follow https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html for that part.

The jupytervolume container simply sets up the jupyter notebook volume for you to use, so that should show an `exit 0` which is successfully run.

> Thank you for considering my questions and I would be happy to provide more information.
> 
> # System info
> Same results in either Ubuntu 16.04 and 18.04
> Docker version 18.09.5, build e8ff056
> docker-compose version 1.24.0, build 0aa59064
> 
> # First set of examples
> Based on https://pacifica-archiveinterface.readthedocs.io/en/latest/exampleusage.html,
> GET, PUT, HEAD all work as expected.
> POST fails because "Client must specify Content-Length" but that is already known in the HEAD operation.
> PATCH fails because "Expected an entity of content type application/json, text/javascript" but the uploaded file is .json as specified in the example.
> Terminal output below.
> 
> > curl -X GET http://localhost:8080
> > {"message": "Pacifica Archive Interface Up and Running"}
> 
> > curl -X PUT -H 'Last-Modified: Sun, 06 Nov 1994 08:49:37 GMT' --upload-file foo.txt http://localhost:8080/12345
> > {"message": "File added to archive", "total_bytes": 36}
> 
> > curl -o foo.txt http://localhost:8080/12345
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 100    36    0    36    0     0   2571      0 --:--:-- --:--:-- --:--:--  2571
> 
> > curl -I -X HEAD http://localhost:8080/12345
> > HTTP/1.1 204 No Content
> > X-Pacifica-File-Storage-Media: disk
> > X-Pacifica-Messsage: File was found
> > X-Content-Length: 36
> > X-Pacifica-File: /srv/12345
> > X-Pacifica-Ctime: 1557152541.06
> > Server: CherryPy/17.4.1
> > Last-Modified: 1557152540.07
> > Allow: DELETE, GET, HEAD, PATCH, POST, PUT
> > Date: Mon, 06 May 2019 14:23:33 GMT
> > Content-Type: application/json
> > X-Pacifica-Bytes-Per-Level: (36L,)
> 
> > curl -X POST http://localhost:8080/12345
> > {"status": "411 Length Required", "message": "Client must specify Content-Length.", "traceback": "Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 630, in respond\n    self._do_respond(path_info)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 682, in _do_respond\n    self.body.process()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py", line 978, in process\n    raise cherrypy.HTTPError(411)\nHTTPError: (411, None)\n", "version": "17.4.1"}

Looks like this one is some sort of error. This is a bug for fixing either the documentation, the code or both in the archive interface.

> > curl -X PATCH --upload-file original_path.json http://localhost:8080/67890
> > {"status": "415 Unsupported Media Type", "message": "Expected an entity of content type application/json, text/javascript", "traceback": "Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 630, in respond\n    self._do_respond(path_info)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 682, in _do_respond\n    self.body.process()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py", line 983, in process\n    super(RequestBody, self).process()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py", line 558, in process\n    self.default_proc()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cperror.py", line 416, in **call**\n    raise self\nHTTPError: (415, u'Expected an entity of content type application/json, text/javascript')\n", "version": "17.4.1"}

This is a documentation issue, I should get more specific for the PATCH method. The idea is to move a file into place on the remote side.

> > cat original_path.json
> > {
> > "path": "/srv/12345"
> > }

The content of the json document should definitely be in the documentation.

If you could pull the snippets for the above and put them as issues into https://github.com/pacifica/pacifica-archiveinterface that would be great.

> # Second set of examples
> In section 4.1 of https://buildmedia.readthedocs.org/media/pdf/pacifica-metadata/latest/pacifica-metadata.pdf,
> as before, PUT works but the database query with GET fails.
> Interestingly (compared to the first set of examples) the POST operation exits OK, but fails to actually update the file.

Seems like you missed something big here, the metadata API port is `8121`. So please try re-running your tests against that port.

> > more create.json
> > {
> > "_id": 127,
> > "email_address": "[john@doe.com](mailto:john@doe.com)",
> > "first_name": "John",
> > "last_name": "Doe",
> > "middle_initial": "",
> > "network_id": "guest"
> > }
> 
> > curl -X PUT -T create.json http://localhost:8080/users
> > {"message": "File added to archive", "total_bytes": 135}
> 
> > curl -X GET 'http://localhost:8080/users?_id=127'
> > {"status": "404 Not Found", "message": "Unexpected query string parameters: _id", "traceback": "Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 630, in respond\n    self._do_respond(path_info)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond\n    response.body = self.handler()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 221, in **call**\n    self.body = self.oldhandler(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in **call**\n    raise sys.exc_info()[1]\nHTTPError: (404, 'Unexpected query string parameters: _id')\n", "version": "17.4.1"}
> 
> > more update.json
> > {
> > "network_id": "example"
> > }
> 
> > curl -X POST -T update.json 'http://localhost:8080/users'
> > {"message": "File was staged", "file": "users"}
> 
> > curl -X GET http://localhost:8080/users
> > {
> > "_id": 127,
> > "email_address": "[john@doe.com](mailto:john@doe.com)",
> > "first_name": "John",
> > "last_name": "Doe",
> > "middle_initial": "",
> > "network_id": "guest"
> > }
> 
> > curl -X POST 'http://localhost:8080/users'
> > {"status": "411 Length Required", "message": "Client must specify Content-Length.", "traceback": "Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 630, in respond\n    self._do_respond(path_info)\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 682, in _do_respond\n    self.body.process()\n  File "/usr/local/lib/python2.7/site-packages/cherrypy/_cpreqbody.py", line 978, in process\n    raise cherrypy.HTTPError(411)\nHTTPError: (411, None)\n", "version": "17.4.1"}

If it helps you can go to the http://localhost:8888 to get Jupyter Notebook and try and run the code examples there as well.

**Comment by stefangary** [comment]
Dear David,

Thank you for the information.  I opened the two issues on pacifica/pacifica-archiveinterface as requested.  And yes, you were exactly right about the trick to get the ElasticSearch container to run.  Now that I have added vm.max_map_count=262144 to my /etc/sysctl.conf, that container comes up fine.

Thank you for pointing out the address issue for the metadata API.  I will test that shortly.

**Comment by stefangary** [comment]
Dear David,

Thanks for pointing out my mistake with the metadata server's address.  But even when I change the address, the lines as given in the examples fail.  Instead, as suggested by your fix to #77 and #78 in pacifica-archiveinterface, the header needs to be specified, e.g.:

> curl -X PUT -H 'Content-Type: application/json' -T create_user.json 'http://localhost:8121/users'

and then it works fine.  I've worked my way through the Jupyter notebook and it was extremely helpful.  Thank you for creating that demo and for pointing it out to me.

Best, Stefan

**Comment by dmlb2000** [comment]
Stefan,

Hopefully we've got you up and running, I'll close this for now.

Thanks,
- David Brown
