### ISSUE TITLE
Migrate pacifica-metadata-mgmt dockerfile and pipeline to pacifica-metadata-mgmt repo

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica#22]
- [ ] Migrate docker/mgmt content to new Dockerfile under https://github.com/pacifica/pacifica-metadata-mgmt
- [ ] Create pipeline to build and push container image to DockerHub
- [ ] Remove or change to consume DockerHub docker image instead of building in docker-compose

**Comment by dmlb2000** [comment]
This one is closed with the #27 alpha release.
