### ISSUE TITLE
Need a process to define what constitutes an approver role versus a general community member

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica#28]
# Pacifica Software Request

## Issue Type

This is a general community issue around approvers or other key community members with more power than just being able to submit issues.

## Discussion

Unless I am mistaken, there are no clear guidelines which describe how to become an official Pacifica team member other than by word of mouth or social reputation.

I think Pacifica would benefit from a clearly established set of guidelines that will determine one's ability to obtain more responsibility within the Pacifica ecosystem. These rights and privileges should come with power and responsibility. They should show strong community engagement and/or code contributions. They should be a consumer of the product for some length of time. They should be allowed to merge code if contributions guidelines are being met by submitters and there is some level of community consensus. There should be a timeline left open for discussions to happen freely and openly so code isn't being snuck into into various services without the community be made aware.

This is just a starting point but this needs to happen if we are to establish a trusted relationship with the Pacifica FOSS community.

**Comment by dmlb2000** [comment]
Pacifica is still pretty small project, I'd like to discuss a better contribution guidelines document at some point but I don't think it's that complicated right now.

The ability to contribute has always been pull requests, pull requests, pull requests. Any roles or permissions beyond that show some scale to the project. However, I'm not seeing the volume to warrant the effort to setup those roles and permissions.

## Quality Code Contributions

The first thing I look for are quality pull requests. This means displaying the ability to accept and incorporate criticisms from the community into your code. When the quality of pull requests becomes trivial to review and the volume becomes overly burdensome for me to merge, then we can discuss assigning elevated privileges to do the merge yourself.

The ability for me to merge code and create tags has not been overly burdensome to complete yet. I'm not going to put a quantitative measure on any of this as the person getting the privileges needs to have a qualitative assessment of their contributions before that happens. 

If you feel someone needs elevated privileges for some repositories you can put an issue into this repository to ask for those privileges. Then we can start an objective assessment about the individuals contributions.
