### ISSUE TITLE
Consider lock in appropriate sub-projects for peewee <3.6

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica#9]
@dmlb2000 
Discovered a build bug with peewee `>=3.6`

[peewee.log](https://github.com/pacifica/pacifica/files/2203892/peewee.log)

**Comment by dmlb2000** [comment]
Not sure what the issue was with this build... I rebuilt the peewee related projects in travis and wasn't able to reproduce the issue you have in your log...

**Comment by dmlb2000** [comment]
https://github.com/coleifer/peewee/issues/1677

Appropriate spot for the issue... hopefully he'll take care of it.
